default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: test_db
  username: postgres
  password: password
  host: localhost
  port: 5432

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: smartlibraryhub_db
  username: smartlibraryhub_db_user
  password: <%= ENV['DB_PASSWORD'] %>
  host: dpg-d1m10jili9vc73ef88ag-a
  port: 5432
