default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: smartlibraryhub_development
  username: postgres
  password: ayQsTOzFODXjzTKlQCFn3P1GYdJQX1p3
  host: localhost

test:
  <<: *default
  database: smartlibraryhub_test
  username: postgres
  password: ayQsTOzFODXjzTKlQCFn3P1GYdJQX1p3
  host: localhost

production:
  <<: *default
  database: smartlibraryhub_db
  username: smartlibraryhub_db_user
  password: <%= ENV['DB_PASSWORD'] %>
  host: dpg-d1m10jili9vc73ef88ag-a
  port: 5432
